### ISSUE TITLE
Garbled text in 'How do Replicas work'

### ISSUE THREAD

**Issue by lkrych** [denizalti/paxosmmc#14]
Hi Deniz, thanks for making this site. I'm using it for reference on a grad school project :). 

While reading through the sections I noticed some strange sentences. I've attached a screenshot comparing the production site (specifically https://paxos.systems/how/) to the source text (gh-pages branch). Do you have any idea what might have happened?

<img width="1484" alt="Screen Shot 2021-10-16 at 3 09 27 PM" src="https://user-images.githubusercontent.com/14141810/137603319-f220b0ec-6c0b-45d0-a669-d6e83cfab7d0.png">

**Comment by nguyen-andrew** [comment]
Hey Leland, I'm also in the OMSCS class with you! I noticed this too. [This commit](https://github.com/denizalti/paxosmmc/commit/725c21f4e03ea2d81b1caeda92f85ba5cd53c91b) seems to have jumbled it up. I did a manual diff of the text and saw this:
![image](https://user-images.githubusercontent.com/37893562/137980308-c887ec0f-0698-4fe2-9959-27c619c27f34.png)
Looks like an update gone wrong. If I strip out some of the highlighted text on the right, I think I get a paragraph that makes more sense:

> Replicas use the Synod protocol to choose a single command for each slot from the proposals they make. For each slot, a set of processes performs the Synod protocol to decide which command should be placed in that particular slot. A particular set of processes that are associated with a slot are commonly referred to as the configuration of that slot. The configuration of a slot contains the leader processes and acceptor processes, but not the replica processes. Leaders receive proposed commands from replicas and are responsible for choosing a single command for the slot. Thus, in order to tolerate  f crash failures, Paxos needs at least f+1 leaders, always leaving at least 1 leader to order the commands proposed by replicas. A replica awaits the decision before actually updating its state and computing a response to send back to the client that issued the request.

**Comment by lkrych** [comment]
Excellent find Andrew!

**Comment by denizalti** [comment]
Thanks for the fix! Merged.
