### ISSUE TITLE
LaTeX formatting not working

### ISSUE THREAD

**Issue by Faboor** [denizalti/paxosmmc#5]
https://github.com/denizalti/paxosmmc/blob/c66cd981ef912538b6ee9f8653ec82df15bd884e/docs/leader.html#L283
The `\textbf{adopted}` is shown raw on the [website](http://paxos.systems/leader.html).

Same for https://github.com/denizalti/paxosmmc/blob/c66cd981ef912538b6ee9f8653ec82df15bd884e/docs/leader.html#L378
and 
https://github.com/denizalti/paxosmmc/blob/c66cd981ef912538b6ee9f8653ec82df15bd884e/docs/leader.html#L380

**Comment by denizalti** [comment]
Thank you to both of you!
