### ISSUE TITLE
Tiny inconsistency

### ISSUE THREAD

**Issue by kaimast** [denizalti/paxosmmc#7]
https://github.com/denizalti/paxosmmc/blob/14eea0de1891433060fe4349782c026add2fb406/code/initial/leader.py#L55

Hi Deniz!

Correct me if I'm wrong, but I think to match with your pseudo code this assignment should be inside the if statement.

**Comment by denizalti** [comment]
Hi!
Yes, I corrected the issue on both the initial and backoff leaders, just pushed the changes.

Thank you for reporting the issue!

Best,
Deniz
